@baseUrl = http://localhost:3000/api
@parentCommentId = 64bbfe8eb2a8a5874b75719f

# @name getTopLevelComments
GET {{baseUrl}}/comments HTTP/1.1

###

# @name getNestedComments
GET {{baseUrl}}/comments?parentId={{parentCommentId}} HTTP/1.1

###

# @name postComment
POST {{baseUrl}}/comments HTTP/1.1
Content-Type: application/json

{
    "text": "Pear character lifting some weights saying 'Keep it up'",
    "userId": "64bbf31f5b408dedbfe6d0ea",
    "parentId": "{{parentCommentId}}"
}
